version: '2'
services:
  lint-shellcheck:
    image: koalaman/shellcheck-alpine:v0.8.0@sha256:f42fde76d2d14a645a848826e54a4d650150e151d9c81057c898da89a82c8a56
    volumes:
      - ".:/plugin:ro"
    entrypoint: sh
    command:
      - -c
      - 'shellcheck /plugin/hooks/*'

  lint-plugin:
    image: buildkite/plugin-linter:v2.0.4@sha256:7c5ab788c569585723f4a5a9e701e23feb385b8ccdd083e76cf0e85b6d490b32
    volumes:
      - ".:/plugin:ro"
    command:
      - --id=planetscale/vault-oidc-auth

  tests:
    image: buildkite/plugin-tester:v4.0.0@sha256:73958fc0768b18ec691e9def050dbc25f814411c9901abfac8cd1f2f361ce8d5
    volumes:
      - ".:/plugin:ro"
